### ISSUE TITLE
Option for selecting resolution in start menu

### ISSUE THREAD

**Issue by MolbOrg** [moonwards1/Moonwards-Virtual-Moon#20]
have an option for selecting resolution in start menu - fullscreen, window mode

**Comment by briligg** [comment]
And this would be for handling performance?

**Comment by briligg** [comment]
The window can be resized by dragging the corners, so i don't know if it is useful putting such options in the UI

**Comment by MolbOrg** [comment]
yeah, doubt it myself now, probably UI enhancements category or be replaced with at least selection windowed/full-screen option
definitely as wishes category as for now

**Comment by briligg** [comment]
The UI needs a lot of work. Once it is better defined there may be a place for maybe a drop-down short list of resolutions. That may be a useful option for people wanting to make videos of gameplay, for instance. Or picking from a short list might be more convenient for some people.

**Comment by Gyrth** [comment]
I've added a resolutions dropdown to my own project. It's not that difficult to implement, but yeah, not really needed since you can just resize the window. A different scenario would be to use a lower resolution while being fullscreen. That's quite useful for people running on low end hardware and that would need a setting in-game. Not really a priority but something to consider.

**Comment by Gyrth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Window Resolution](https://trello.com/c/ahEjKpjo/23-window-resolution)
