### ISSUE TITLE
Assess quality of the audio tracks for the tour

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#328]
Please listen to the tracks and assess their clarity as explanations, the quality of the sound and presentation, and entertainment value. They need to successfully sell the town and they have to be good.

The tracks are located in `Assets/ Sounds/ Audio_Tour`

Related: #270

**Comment by SiudaPL** [comment]
The voice itself is quite good, so we should be able to avoid outsourcing entire thing to audio pros.
However, there are some noises in the background - especially you can hear a click once in a while, like:

- *Audio_Tour_Indoor.ogg* at the very end or
- *Audio_Tour_Indoor3.ogg* at *0:27*.

I tried to run some audio filter in *Audacity* to silence them but there doesn't seem to be any improvement. Maybe it possible to filter out quite noises while doing the record itself. Put bar on input somewhere, although I don't know if that is possible since I'm not that experienced with audio tools.

Also it may be best to record each sentence separately, rather than entire topic at once. It will then require to edit the file manually and put the small pause between the sentences with programs. However it will allow for perfect silence at the breaks and smooth out the edges if required.

Maybe playing some, rather quiet music, during the audio tour may help to hide the imperfections.

**Comment by Moonwards** [comment]
I'll look for those clicks and take them out manually. I did it in Audacity and applied filters for noise, but it only helps up to a point, and this is a rather noisy place. 

Music would be nice but selecting some and matching it up is a whole other undertaking. I think that would best be done so there is background music all the time, that changes by hab and activity. It's a job we can get to at some point. Maybe it's time to write it up as an issue.

I actually did record each sentence separately, so I'm glad that was smooth enough that you can't tell.
