### ISSUE TITLE
Reflection of Earth in mirrors of Hexpane Windows

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#338]
![image](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ec6bdd53c5016001672f383)

The purpose of these window wells is that they reflect in the Earth. Currently they only reflect the sky, 
[Mirror-Reflecting-Earth.blend](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f75f6436ddf5200112638a9)

**Comment by Zach777** [comment]
Since I was in the wrong issue before, I will repost what I posted before.

How detailed are the reflections suppose to be?
 For perfect reflections, we could possible create a second viewport and place it onto the reflecting object.
For imperfect reflections, we could create a shader that loads a pixelized image of what is expected to be reflected on the reflecting body. 

 For bodies that are going to reflect imperfectly and be moving, we could have lightpoints around the world that the body displays on itself when in the correct position.

Will we need moving perfectly reflective bodies?

**Comment by Moonwards** [comment]
@Zach777 For this, yes, it is perfect reflection. 

This case is a static object. Later it might be an object that changes at different times, but it wouldn't move in real time, it just might be different on different occasions. 

For now, I can't think of anything that needs reflection of moving objects.

**Comment by Moonwards** [comment]
This blender file demonstrates how a plane of sufficient size with the starry sky and Earth on it can be used to produce the desired effect - at least close enough. In the blender file, there is an actual mirror accurately reflecting the plane. It gives a sense of the dynamics as you move around in the habitat relative to the mirror

[Mirror-Reflecting-Earth.blend](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f7510176ddf52001125f123)

**Comment by Moonwards** [comment]
Here is the image that was used

![Earth-in-starry-square.jpg](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f7515da0d832b001117b843)
