### ISSUE TITLE
Set up Rocket display

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#364]
@Gyrth made this but it needs to be set up again. The rocket is not done as a .glb and exporting it as such has been a problem. It may be necessary to place it in its old format for now, until that problem is resolved. See #391
- [ ] Build a simple interface, on top of Godot's 2D and 3D view, that will allow non-coders to develop slides easily, with basic functionality
- [ ] Refactor the display's and slide's code
- [ ] Add ability to develop movable camera into slide's viewport
- [ ] Add extra minor features to the display / slide component

**Comment by SiudaPL** [comment]
@KimberleyHolder I assume we want that in-game display with slides, that player can watch and switch the slides with the clicks like we had before, right?

**Comment by Moonwards** [comment]
@SiudaPL Gyrth set up the rocket display with animations before. A camera moved around and showed the rocket from different vantage points so that the inner mechanisms of it could be shown, which moved as they would if the rocket was built. Text showed on the bottom of the screen

We have 3d objects at our disposal, already loaded, and the ability to add images, videos, and animations. I think it will be a big design challenge to find the best way to use each of those to convey information in a way that is engaging, clear, and efficient. A 'slideshow' is the only word i know that is on the general topic, but technology has moved beyond it. 'Interactable' i suppose is the updated term. 

A specialist in animations can be brought in at some point. For now - this rocket has working parts that have been animated. If you scroll down in the left sidebar in GitKraken and click on `old-demo-reference` in the TAGs section, that commit should have that file. (I'll find it once i'm finished with something, i don't want to switch to such an old commit right now.)

**Comment by SiudaPL** [comment]
@KimberleyHolder OK, I see the @Gyrth work. It is the *RocketDisplay* *tscn* and *gd*. So assuming from when I left working on the slides, we would need to add some extra features then:

- slide time-out: slide would end and auto move to next one for a smooth experience, or impenitent viewer can click "Next" button on his own.
- code to move and set up cameras. This is something that can be copied from @Gyrth work, although not without working on it.

Overall I think the more stuff can be set up from the *3D* view in *Godot* the better. It will allow for community contributors to add new ones relatively easy. I will work on some sort of simple interface for our slides, since neither my work, or Gyryth's is polished and finished, as of now.

**Comment by Moonwards** [comment]
Ok, that all sounds good. Easy community contributions is an important point.

I have struggled to try to understand how best to make these presentations show information really well. I think this will need to be expanded on over time to include more options and functions.

For instance, maybe it would help if a user could move the camera between slides. Say, after the next slidein the presentation is loaded (the camera moves, and the next area with text - or maybe other things - appears), then after that the user is able to move the camera around, until they click to go to the next slide, and that would make the camera go to the next set spot.

Some way to highlight pieces of a model would also be helpful.
