### ISSUE TITLE
There are two main.gd files

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#71]
res://_tests/Camera/camera_add/Main.gd

and

res://scripts/Main.gd

these should be renamed to avoid confusion

**Comment by MolbOrg** [comment]
_tests stuff not necessarily should be considered as unique resources, as name wise, it more liek a playground which can and contain also other godot projects.
_tests is for keeping recipes and testings which worth keeping and sharing.

What it should not have is to have is an intersection in files with other resources of the project, they have to be standalone self contained scenes and code.

so something like it was in #63 should not be there.

**Comment by Moonwards** [comment]
Should that stuff be kept as part of the main project though? That folder just seems to grow and it's hard to find stuff in it.

**Comment by TheDuriel** [comment]
Files should not share names, even if its in _tests. The script editor for example wont make that distinction. One of them will need to be renamed. Presumably the one in _tests.

_honestly_ _tests should not be part of the repo unless its specifically meant to be "tested". If you're making a local test, don't add the files to a PR.

**Comment by Moonwards** [comment]
We have three open issues right now that are about nothing except renaming a file, and they haven't been resolved for days. These should have been closed the same day. @MolbOrg please do this one, since you have raised objections on two of those issues. I want you to get used to the focus on optimized organization this is about. 

We can find better ways to create a space for experimentation and examples. _tests isn't it.
