### ISSUE TITLE
Rocket display text is obscured

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#750]
This issue calls for changing the layout of the text for this presentation.

![Screenshot from 2020-11-05 15-39-34.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5fa4727b6ddf520011336e6e)

I think that it will need to be moved over so the right side of it is flush against the right side of the game window, and moved so that it's above the main row of app keys. The text will need to come down a few points in size so that it always fits comfortably in that space - it can be as large as wiill fit in that space at the default window size of 1280 x 720, for the longest section of text (the first one).

See issue # 751 regarding positioning of other HUD elements

**Comment by Zach777** [comment]
The camera work was designed to with that text layout in mind. 
The original intended mechanic was for the Hud to disappear when you start the Rocket Display. I think it would be best to implement that feature now.

**Comment by Moonwards** [comment]
That's true, but there's been a lot of water under the bridge since then. That was done over a year ago in very different conditions.
I wouldn't call this a major change to the intentions of the design, but i can ask about it.

If we have things locking out the HUD at times, that feels to me like it will become more of a problem than it's worth, sooner or later. The game depends on engagement by a community, I think it's better to allow the social features to continue to function.

**Comment by Zach777** [comment]
@Moonwards 

I am not too worried about Chat blocking things as it is resizeable/hideable from the player. 
 Hud features like the camera of the ToolsBar needs to be accessible at all times you are right. 
 Who was the person who originally designed the camera for the rocket display? If they are still active they might be able to change it super easily.

 The issue is that I do not know what would be the best way to showcase something while having text describing it while having the full Hud active.

 Perhaps we can just have an animation for Hud disappearing that shows what button to press before fading away? Or a permanent showcase saying what button to hit to activate Hud.
 This could be useful too as we can program a hide Hud button for any situation because of that.

**Comment by Moonwards** [comment]
The layout I describe seems to me like it would work fine without any need to resize or hide the chat, in case something comes in while you are watching the presentation, or indeed if you are talking to someone else who is also watching it.  I think that arrangement allows the full HUD - other than the app buttons, which I can't imagine why you'd want to use then - to be accessible while also allowing the full text to display. You just have to make the text smaller, which there is room to do. Or create scrolling.

**Comment by Moonwards** [comment]
@Zach777 There has been a regression on this one.

**Comment by Zach777** [comment]
@Moonwards I recall another developer started working on this. Gyrth I think. Does he have a branch I can look at.
 The issue with moving the UI is that I have to redo how the camera is setup for the scene.
